# site properties and page defaults
title: Marine Ecological and Evolutionary Genomics | GEOMAR
subtitle: 
description: The marine ecological and evolutionary genomics group at GEOMAR seeks to understand how species rapidly evolve across environmental and temporal gradients and in response to changing environments due to human driven global change. We focus on marine zooplankton and fish and use diverse approaches including physiological, transcriptomic, and population genomics to investigate the mechanistic and evolutionary underpinnings of ecologically relevant traits. 
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: contact@brennan-research.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: brennan-research
  twitter: brennan-research
  youtube: brennan-research

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
